package com.easy.service.dao;

import com.easy.service.dao.pojo.User;


public interface UserDao {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_user
     *
     * @mbggenerated
     */
	Integer insert(User user);

}
